### ISSUE TITLE
missing pkg: github.com/tonistiigi/fsutil/util

### ISSUE THREAD

**Issue by AkihiroSuda** [tonistiigi/fsutil#3]
`github.com/tonistiigi/fsutil/util` is referenced from CLIs but not commited to git

**Comment by AkihiroSuda** [comment]
@tonistiigi PTAL?

**Comment by tonistiigi** [comment]
@AkihiroSuda hmm.. I think it was accidentally removed in 719ce2a5e9357de73b975ae1febef460c2b2b3c1

**Comment by AkihiroSuda** [comment]
opened #5
