### ISSUE TITLE
Debian packaging

### ISSUE THREAD

**Issue by suntong** [tonistiigi/fsutil#76]
Following up with https://github.com/tonistiigi/fsutil/issues/43

I'm packaging `fsutil` in preparing for the upcoming docker cli packaging.  
However, I'm facing difficulties doing that due the test needs to be done as root. 
There is a lengthy discussion in debian-go dlist at
https://lists.debian.org/debian-go/2020/03/msg00106.html

Do you have any suggestions how I can proceed?  
If I need to change the test files to incorporate Debian packaging, would you accept my PRs?

thanks

**Comment by suntong** [comment]
My plan is to mark all failed test to be skipped at Debian-build time with a call to the `Skip` method --

```
    if testing.Short() {
        t.Skip("skipping test that would fail in Debian-build.")
    }
```

However, the down side is that, it also means the test in short mode has a ambiguous meaning. 

Due to my limited knowledge, this is the only way I know that can make it working.

**Comment by suntong** [comment]
> the down side is that, it also means the test in short mode has an ambiguous meaning

This will remove the ambiguity:

    if testing.Short() && len(os.Getenv("DEB_BUILD_ARCH_OS")) != 0  {
        t.Skip("skipping test that would fail in Debian-build.")
    }

So now the changes will not have side effects.

**Comment by tonistiigi** [comment]
we can just skip things that require root. We already have smth like this https://github.com/tonistiigi/fsutil/blob/013a9fe6aee2d1658457075bf9e688bc8c0be2e0/diskwriter_test.go#L21

**Comment by suntong** [comment]
Thanks @tonistiigi, I'll skip the rest that require root and failed in Debian packaging, and submit a PR...

**Comment by suntong** [comment]
Done. Please approve https://github.com/tonistiigi/fsutil/pull/78 and tag a new release.
