### ISSUE TITLE
copyFileContent broken on zfs (in some cases)

### ISSUE THREAD

**Issue by jmesmon** [tonistiigi/fsutil#96]
See https://github.com/moby/moby/issues/41866

Basically, need to add `EINVAL` on this line: https://github.com/tonistiigi/fsutil/blob/0834f99b7b85462efb69b4f571a4fa3ca7da5ac9/copy/copy_linux.go#L92

Also worth considering if any error should cause the fallback.

I haven't isolated the kernel version/zfs version that causes the issue. My kernel & zfs version are posted in the moby ticket linked above.

There's also an identical issue in containerd/continuity: https://github.com/containerd/continuity/issues/176

**Comment by tonistiigi** [comment]
@jmesmon Send the patches to the affected repos. Match the behavior/argumentation to https://github.com/golang/go/blob/5f646f0a984d43a2e9e99a1338145a862fef425e/src/internal/poll/copy_file_range_linux.go#L90-L112
